// === LEVELS DEFINITIONS ===
// TODOs 7, 11, and 12 will require changes to this section
const LEVELS = [
  {
    name: "Level 1",
    speed: 2,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 1600, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 1552, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 1504, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 1456, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 1408, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 1360, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 1312, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 1624, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 1850, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2700, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2748, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2796, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3800, y: groundY - 148, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 4300, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 6800, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 6400, y: groundY, speedX: -3.8, contactHealthChange: -90},
      { type: "obstacle", kind: "spikes", x: 7500, y: groundY - 100, speedX: -3.5, contactHealthChange: -40},
      { type: "enemy", kind: "bug", x: 2600, y: groundY, speedX: -3.6, hp: 2},
      { type: "enemy", kind: "bug", x: 3300, y: groundY, speedX: -3.6, hp: 2},
      { type: "enemy", kind: "bug", x: 5500, y: groundY, speedX: -3.8, hp: 1},
      { type: "enemy", kind: "bug", x: 5650, y: groundY, speedX: -3.8, hp: 1},
      { type: "enemy", kind: "bug", x: 5800, y: groundY, speedX: -3.8, hp: 1},
      { type: "enemy", kind: "bug", x: 5950, y: groundY, speedX: -3.8, hp: 1},
      { type: "enemy", kind: "bug", x: 6100, y: groundY, speedX: -3.8, hp: 1},
      { type: "enemy", kind: "bug", x: 6250, y: groundY, speedX: -3.8, hp: 1},
      { type: "enemy", kind: "bug", x: 6325, y: groundY, speedX: -3.8, hp: 1},
      { type: "enemy", kind: "bug", x: 6400, y: groundY, speedX: -3.8, hp: 1},
      { type: "enemy", kind: "bug", x: 6475, y: groundY, speedX: -3.8, hp: 1},
      { type: "enemy", kind: "bug", x: 9000, y: groundY, speedX: -70, contactHealthChange: -50, hp: 1},
      { type: "enemy", kind: "bug", x: 9000, y: groundY, speedX: -3.5, contactHealthChange: -100, width:300, height:300, hitWidth: 300, hitHeight: 300, hp: 6},
      { type: "enemy", kind: "bug", x: 7500, y: groundY, speedX: -3.5, contactHealthChange: -100, width:5, height:5, hitWidth: 10, hitHeight: 10},
      { type: "powerup", kind: "healthUp", x: 1750, y: groundY - 50, speedX: -3.5},
      { type: "powerup", kind: "healthUp", x: 4000, y: groundY - 200, speedX: -3.5},
      { type: "powerup", kind: "healthUp", x: 7000, y: groundY - 50, speedX: -3.5},
      {
        type: "platform",
        kind: "basicPlatform",
        x: 3800,
        y: groundY - 100,
        speedX: -3.5,
      },
      { type: "platform", kind: "basicPlatform", x: 3600, y: groundY - 60, speedX: -3.5},
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1000,
        y: groundY - 60,
        speedX: -3.5,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1200,
        y: groundY - 100,
        speedX: -3.5,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 7400,
        y: groundY - 60,
        speedX: -3.5,
      },

      { type: "goal", kind: "flag", x: 10000, y: groundY, speedX: -3.5},
    ],
  },
  {
    name: "Level 2",
    speed: 3,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 1600, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2200, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2248, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2296, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2344, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2392, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2440, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2488, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2536, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2584, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2632, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2680, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2728, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2776, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2824, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2872, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2920, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2968, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3016, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3064, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3102, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3150, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3198, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3246, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3292, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3340, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3388, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3436, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3484, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3532, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3580, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 5075, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 5250, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 5700, y: groundY - 110, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 5800, y: groundY - 110, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 5900, y: groundY - 110, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 7300, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 7600, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "enemy", kind: "bug", x: 4600, y: groundY, speedX: -3.6, hp: 2},
      { type: "enemy", kind: "bug", x: 5100, y: groundY - 100, speedX: -3.5, contactHealthChange: -70, width:20, height:20, hitWidth: 10, hitHeight: 10},
      { type: "enemy", kind: "bug", x: 6500, y: groundY, speedX: -3.8, hp: 2},
      { type: "enemy", kind: "bug", x: 7300, y: groundY, speedX: -4.0, hp: 2},
      { type: "enemy", kind: "bug", x: 11000, y: groundY, speedX: -7.0, hp: 2},
      { type: "enemy", kind: "bug", x: 12100, y: groundY, speedX: -7.0, hp: 2},
      { type: "enemy", kind: "bug", x: 8700, y: groundY, speedX: -3.6, contactHealthChange: -90, width:20, height:20, hitWidth: 10, hitHeight: 10},
      { type: "enemy", kind: "bug", x: 14870, y: groundY - 120, speedX: -8, contactHealthChange: -90, width:20, height:20, hitWidth: 10, hitHeight: 10},
      { type: "enemy", kind: "bug", x: 9500, y: groundY, speedX: -3.6, contactHealthChange: -90, width:10, height:10, hitWidth: 10, hitHeight: 10},
      { type: "enemy", kind: "bug", x: 9000, y: groundY, speedX: -70, contactHealthChange: -70, hp: 1},
      { type: "powerup", kind: "healthUp", x: 1700, y: groundY - 50, speedX: -3.5},
      { type: "powerup", kind: "healthUp", x: 5800, y: groundY - 10, speedX: -3.5},
      { type: "powerup", kind: "healthUp", x: 8550, y: groundY - 120, speedX: -3.5},
      {
        type: "platform",
        kind: "basicPlatform",
        x: 2200,
        y: groundY - 60,
        speedX: -3.5
      },
      { type: "platform", kind: "basicPlatform", x: 2600, y: groundY - 60, speedX: -3.5 },
      { type: "platform", kind: "basicPlatform", x: 3000, y: groundY - 60, speedX: -3.5, width: 50, hitWidth: 50},
      { type: "platform", kind: "basicPlatform", x: 3350, y: groundY - 60, speedX: -3.5, width: 25, hitWidth: 25},
      { type: "platform", kind: "basicPlatform", x: 5600, y: groundY - 70, speedX: -3.5 },
      { type: "platform", kind: "basicPlatform", x: 8500, y: groundY - 70, speedX: -3.5 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 5000,
        y: groundY - 50,
        speedX: -3.5
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 5800,
        y: groundY - 70,
        speedX: -3.5
      },

      { type: "goal", kind: "flag", x: 10000, y: groundY, speedX: -3.5 },
    ],
  },
  {
    name: "Level 3",
    speed: 4,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 1700, y: groundY, speedX: -3.5, contactHealthChange: -50, hp: Infinity},
      { type: "obstacle", kind: "spikes", x: 1900, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 1948, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2250, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2298, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2346, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2776, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2824, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2872, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2920, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 2968, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3016, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3064, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3102, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3150, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3198, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3246, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3292, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3340, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3388, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3436, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3484, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3532, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3580, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3628, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3676, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3724, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3772, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3820, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3868, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3916, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 3964, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 4012, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 4350, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 6430, y: groundY-20, speedX: -3.6, contactHealthChange: -40, width: 24, height: 24, hitWidth: 24, hitWidth: 24},
      { type: "obstacle", kind: "spikes", x: 7200, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 7325, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 7373, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 7421, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 7469, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "obstacle", kind: "spikes", x: 7507, y: groundY, speedX: -3.5, contactHealthChange: -40},
      { type: "enemy", kind: "bug", x: 4900, y: groundY, speedX: -3.6, hp: 2},
      { type: "enemy", kind: "bug", x: 5500, y: groundY, speedX: -3.6, hp: 2},
      { type: "enemy", kind: "bug", x: 6400, y: groundY, speedX: -3.6, hp: 2},
      { type: "enemy", kind: "bug", x: 7160, y: groundY - 30, speedX: -3.7, contactHealthChange: -90, width:20, height:20, hitWidth: 10, hitHeight: 10, hp: Infinity},
      { type: "enemy", kind: "bug", x: 9500, y: groundY, speedX: -3.6, contactHealthChange: -100, width:10, height:10, hitWidth: 10, hitHeight: 10},
      { type: "enemy", kind: "bug", x: 12000, y: groundY, speedX: -70, contactHealthChange: -50, hp: 1},
      { type: "enemy", kind: "bug", x: 108000, y: groundY, speedX: -80, contactHealthChange: -100, hp: Infinity},
      {type: "powerup", kind: "healthUp", x: 2600, y: groundY - 10, speedX: -3.5},
      {type: "powerup", kind: "healthUp", x: 5475, y: groundY - 10, speedX: -3.5},
      {type: "powerup", kind: "healthUp", x: 7000, y: groundY - 20, speedX: -3.5},
      {type: "powerup", kind: "healthUp", x: 7800, y: groundY - 20, speedX: -3.5},


      { type: "platform", kind: "basicPlatform", x: 2850, y: groundY - 70, speedX: -3.5, width: 50, hitWidth: 50},
      { type: "platform", kind: "basicPlatform", x: 3200, y: groundY - 70, speedX: -3.5 },
      { type: "platform", kind: "basicPlatform", x: 3750, y: groundY - 60, speedX: -3.5, width: 25, hitWidth: 25},
      { type: "platform", kind: "basicPlatform", x: 6900, y: groundY - 70, speedX: -3.5, hp: 0},
      { type: "platform", kind: "basicPlatform", x: 7300, y: groundY - 90, speedX: -3.5, width: 25, hitWidth: 25},
      { type: "goal", kind: "flag", x: 10000, y: groundY, speedX: -3.5 },
    ]
  }
];

let currentLevel = LEVELS[0];
let currentLevelIndex = 0;
// === END LEVELS DEFINITIONS ===

// === DEFAULT VALUES FOR EACH "type" AND "kind" OF OBJECT (STUDENT-EDITABLE) ===
const DEFAULT_VALUES = {
  obstacle: {
    spikes: {
      imageUrl: "images/interactable/spikes.png",
      width: 48,
      height: 48,
      hitWidth: 40,
      hitHeight: 44,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: -20,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: false,
    },
  },
  enemy: {
    bug: {
      imageUrl: "images/interactable/bug.png",
      width: 75,
      height: 75,
      hitWidth: 75,
      hitHeight: 75,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 75,
      contactHealthChange: -30,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 50,
      hp: 3,
      collect: false,
    },
  },
  powerup: {
    healthUp: {
      imageUrl: "images/interactable/health-up.png",
      width: 32,
      height: 32,
      hitWidth: 32,
      hitHeight: 32,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 32,
      contactHealthChange: +20,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  goal: {
    flag: {
      imageUrl: "images/interactable/flag.png",
      width: 100,
      height: 100,
      hitWidth: 100,
      hitHeight: 100,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: 0,
      contactScoreChange: +100,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  platform: {
    basicPlatform: {
      imageUrl: "images/interactable/basic-platform.png",
      width: 200,
      height: 50,
      hitWidth: 200,
      hitHeight: 50,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 50,
      contactHealthChange: 0,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: Infinity,
      collect: false,
    },
  },
};
// === END DEFAULT VALUES ===
